#1 Added Members Page, Member Progress, Member Tasks
Dev-incubator/DIMS.UI-11 pull request #1
Opened 2020-11-02 13:13 UTC by Werton-Wad

2020-11-02 19:46 UTC, maximsan requested changes
Hello! I left some notes. Please fix them. Don't forget to add prop-types, unit-tests for all you helpers. It's better to use scss(sass) or post.css(module) for css. You will not work with pure css on your first project in the firm. Thanks!

2020-11-02 19:46 UTC, maximsan commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&display=swap" rel="stylesheet" />
if it's possible install you font as a npm package and add in entry file

2020-11-02 19:46 UTC, maximsan commented on src/components/Button/index.js
> +const Button = (props) => {
spread it here directly, it looks better (^_^)

2020-11-02 19:46 UTC, maximsan commented on src/components/Button/index.js
> +    <button className={buttonClass} onClick={handleClick}>
I believe you can pass the `handleClick` as `onClick` if you don't do something special with it

2020-11-02 19:46 UTC, maximsan commented on src/components/DimsApp/index.js
> +  };
please format your code, between all logical parts should be indentation

2020-11-02 19:46 UTC, maximsan commented on src/components/DimsApp/index.js
> +    const membersDB = await db.getMembers();
wrap with try catch

2020-11-02 19:46 UTC, maximsan commented on src/components/DimsApp/index.js
> +      this.setState({ members: membersDB });
you short props `this.setState({ members })`

2020-11-02 19:46 UTC, maximsan commented on src/components/DimsApp/index.js
> +      const members = createData(10);
the logic should be in your `getMembers` method

2020-11-02 19:46 UTC, maximsan commented on src/components/DimsApp/index.js
> +      Promise.all(members.map((member) => db.addMemberToDb(member)));
you need to await `members`, because it other case it's array of promises..
but I believe you don't need this code

2020-11-02 19:46 UTC, maximsan commented on src/components/DimsApp/index.js
> +class DimsApp extends React.Component {
use `PureComponent`, read about it

2020-11-02 19:46 UTC, maximsan commented on src/components/DimsApp/index.js
> +    this.setState({ component: MemberTasks, currentMember: member, isModal: !this.state.isModal });
it's big reference objects, use setState with function

2020-11-02 19:46 UTC, maximsan commented on src/components/DimsApp/index.js
> +    this.setState({ currentMember: member, component: MemberProgress, isModal: !this.state.isModal });
it looks the same as `handleMemberTasks` method, refactor it

2020-11-02 19:46 UTC, maximsan commented on src/components/DimsApp/index.js
> +        {isModal && <ModalWindow toggleModal={this.toggleModal} {...this.state} />}
it's better not to spread big data object, but pass all props explicitly

2020-11-02 19:46 UTC, maximsan commented on src/components/MemberProgress/index.js
> +const MemberProgress = ({ currentMember: member }) => {
do we really need to rename it ? I believe it's redundant, the prop is only here, just pass it as member

2020-11-02 19:46 UTC, maximsan commented on src/components/MemberProgress/index.js
> +  let id = 1;
it's redundant

2020-11-02 19:46 UTC, maximsan commented on src/components/MemberProgress/index.js
> +      <div className='task-message'>{member.firstName + ' ' + member.lastName} progress:</div>
create helper for fullName

2020-11-02 19:46 UTC, maximsan commented on src/components/MemberProgress/index.js
> +              <tr key={id}>
dont forget to use composite key

2020-11-02 19:46 UTC, maximsan commented on src/components/MemberTasks/index.js
> +  let id = 1;
it's redundant

2020-11-02 19:46 UTC, maximsan commented on src/components/MemberTasks/index.js
> +              <tr key={id}>
dont forget to use composite key

2020-11-02 19:46 UTC, maximsan commented on src/components/Members/index.js
> +  let id = 1;
the same is here

2020-11-02 19:46 UTC, maximsan commented on src/components/Members/index.js
> +              <tr key={id}>
the same is here

2020-11-02 19:46 UTC, maximsan commented on src/components/Members/index.js
> +                <td>{member.firstName + ' ' + member.lastName}</td>
the same is here

2020-11-02 19:46 UTC, maximsan commented on src/components/Members/index.js
> +                    <Button buttonClass='btn' buttonName='Progress' handleClick={() => handleMemberProgress(member)} />
it's better to save call in method

2020-11-02 19:46 UTC, maximsan commented on src/components/Members/index.js
> +                    <Button buttonClass='btn' buttonName='Tasks' handleClick={() => handleMemberTasks(member)} />
it's better to save call in method

2020-11-02 19:46 UTC, maximsan commented on src/components/ModalWindow/index.js
> +  console.log(tasks);
remove

2020-11-02 19:46 UTC, maximsan commented on src/components/ModalWindow/index.js
> +  let { toggleModal, tasks, component: Component } = props;
use const for not changeable variables..
I'm not sure that you need the approach with `Component` here.

2020-11-02 19:46 UTC, maximsan commented on src/components/ModalWindow/modal.css
> +  width: 20px;
use rem if it's possible

2020-11-02 19:46 UTC, maximsan commented on src/components/Spinner/index.js
> +    </svg>
It's ok now, but It's better to create it with only css later

2020-11-02 19:46 UTC, maximsan commented on src/components/utilis/index.js
> +    id: id++,
I believe you can create unic identifier from something else

2020-11-02 19:46 UTC, maximsan commented on src/firebase.js
> +    .add(member);
add error handling

2020-11-02 19:46 UTC, maximsan commented on src/firebase.js
> +    .get();
add error handling

2020-11-02 19:46 UTC, maximsan commented on src/firebase.js
> +    .collection('members')
this part can be reusable, because it's common

2020-11-02 19:46 UTC, maximsan commented on src/index.css
> +audio,
I believe it's redundant, CRA has build-in reset.css for this

2020-11-05 11:25 UTC, Werton-Wad commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&display=swap" rel="stylesheet" />
```suggestion 
@import url('https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&display=swap');
```

2020-11-05 11:26 UTC, Werton-Wad commented on src/components/Button/index.js
> +const Button = (props) => {
```suggestion 
const Button = ({ buttonName, buttonClass, handleClick }) => {
```

2020-11-05 11:30 UTC, Werton-Wad commented on src/components/DimsApp/index.js
> +    const membersDB = await db.getMembers();
```suggestion
  async componentDidMount() {
    try {
      const members = await db.getMembers();
      this.setState({ members });
    } catch (e) {
      throw e;
    }
  }
```

2020-11-05 11:31 UTC, Werton-Wad commented on src/components/utilis/index.js
> +    id: id++,
```suggestion
export function generateUser() {
  const randomTasks = createRandomTasks(5);
  return {
    id: faker.random.uuid(),
```

2020-11-05 11:33 UTC, Werton-Wad commented on src/components/DimsApp/index.js
> +      this.setState({ members: membersDB });
```suggestion
async componentDidMount() {
    try {
      const members = await db.getMembers();
      this.setState({ members });
```

2020-11-05 11:34 UTC, Werton-Wad commented on src/components/DimsApp/index.js
> +      const members = createData(10);
``` suggestion
async function getMembers() {
  try {
    await firebase.initializeApp(firebaseConfig);
    const membersDB = await firestoreCollectionMembers().get();
    let members = membersDB.docs.map((doc) => doc.data());
    if (members.length) {
      return members;
    } else {
      members = createData(10);
      members.map(async (member) => await addMemberToDb(member));
      return members;
    }
  } catch (e) {
    throw e;
  }
}
```

2020-11-05 11:36 UTC, Werton-Wad commented on src/components/DimsApp/index.js
> +      Promise.all(members.map((member) => db.addMemberToDb(member)));
i did so
``` suggestion
      members = createData(10);
      members.map(async (member) => await addMemberToDb(member));
```

2020-11-05 11:37 UTC, Werton-Wad commented on src/components/DimsApp/index.js
> +class DimsApp extends React.Component {
``` suggestion 
class DimsApp extends React.PureComponent {
```

2020-11-05 11:38 UTC, Werton-Wad commented on src/components/DimsApp/index.js
> +    this.setState({ component: MemberTasks, currentMember: member, isModal: !this.state.isModal });
```suggestion 
 handleMember = (member, component) => () => {
    this.setState((prevState) => {
      return {
        component,
        currentMember: member,
        isModal: !prevState.isModal,
      };
    });
  };
```

2020-11-05 11:41 UTC, Werton-Wad commented on src/components/DimsApp/index.js
> +    this.setState({ currentMember: member, component: MemberProgress, isModal: !this.state.isModal });
same as above.

2020-11-05 11:41 UTC, Werton-Wad commented on src/components/DimsApp/index.js
> +        {isModal && <ModalWindow toggleModal={this.toggleModal} {...this.state} />}
```suggestion
 const { isModal, members, currentMember, component } = this.state;
    return (
      <div>
        {isModal && <ModalWindow toggleModal={this.toggleModal} member={currentMember} Component={component} />}
```

2020-11-05 11:43 UTC, Werton-Wad commented on src/components/DimsApp/index.js
> +        {isModal && <ModalWindow toggleModal={this.toggleModal} {...this.state} />}
it is badly copied in suggestion, my code is aligned)

2020-11-05 11:43 UTC, Werton-Wad commented on src/components/MemberProgress/index.js
> +const MemberProgress = ({ currentMember: member }) => {
```suggestion 
 const MemberProgress = ({ member }) => {
```

2020-11-05 11:45 UTC, Werton-Wad commented on src/components/MemberProgress/index.js
> +      <div className='task-message'>{member.firstName + ' ' + member.lastName} progress:</div>
did hepler getFullName
```suggestion
export function getFullName(firstName, lastName) {
  return firstName + ' ' + lastName;
}
```

2020-11-05 11:49 UTC, Werton-Wad commented on src/components/Members/index.js
> +                    <Button buttonClass='btn' buttonName='Progress' handleClick={() => handleMemberProgress(member)} />
```suggestion 
<td>{member.age}</td>
                <td>
                  <div className='buttons'>
                    <Button
                      buttonClass='btn'
                      buttonName='Progress'
                      handleClick={handleMember(member, MemberProgress)}
```

2020-11-05 11:51 UTC, Werton-Wad commented on src/components/Members/index.js
> +                    <Button buttonClass='btn' buttonName='Tasks' handleClick={() => handleMemberTasks(member)} />
same as above

2020-11-05 11:51 UTC, Werton-Wad commented on src/components/ModalWindow/index.js
> +  console.log(tasks);
removed that

2020-11-05 11:53 UTC, Werton-Wad commented on src/components/ModalWindow/index.js
> +  let { toggleModal, tasks, component: Component } = props;
fixed it, when I add another component I will do routing, then the logic will change.

2020-11-05 11:54 UTC, Werton-Wad commented on src/components/ModalWindow/modal.css
> +  width: 20px;
```suggestion
 .close-btn {
    cursor: pointer;
    width: 1.5rem;
    height: 1.5rem;
  }
}
```

2020-11-05 11:54 UTC, Werton-Wad commented on src/components/Spinner/index.js
> +    </svg>
ok

2020-11-05 11:56 UTC, Werton-Wad commented on src/firebase.js
> +    .add(member);
```suggestion
 try {
    await firestoreCollectionMembers().add(member);
  } catch (e) {
    throw e;
  }
```

2020-11-05 11:57 UTC, Werton-Wad commented on src/firebase.js
> +    .get();
did same as above

2020-11-05 11:57 UTC, Werton-Wad commented on src/firebase.js
> +    .collection('members')
did function:
```suggestion
function firestoreCollectionMembers() {
  return firebase.firestore().collection('members');
}
```

2020-11-05 12:00 UTC, Werton-Wad commented on src/index.css
> +audio,
I deleted that, added sass, prop-types and did unit-tests for my side functions.

2020-11-05 12:05 UTC, Werton-Wad commented on src/components/Button/index.js
> +    <button className={buttonClass} onClick={handleClick}>
it my method from main component with state.

2020-11-05 12:35 UTC, Werton-Wad commented on src/components/MemberProgress/index.js
> +  let id = 1;
deleted variable id:
```suggestion
  {member.progress.map((item, i) => {
            return (
              <tr key={item.id}>
                <td>{++i}</td>
```

2020-11-05 12:36 UTC, Werton-Wad commented on src/components/MemberProgress/index.js
> +              <tr key={id}>
did key=item.id

2020-11-05 12:37 UTC, Werton-Wad commented on src/components/MemberTasks/index.js
> +  let id = 1;
```suggestion
 {member.tasks.map((task, i) => {
            return (
              <tr key={task.id}>
                <td>{++i}</td>
```

2020-11-05 12:38 UTC, Werton-Wad commented on src/components/MemberTasks/index.js
> +              <tr key={id}>
did as above

2020-11-05 12:38 UTC, Werton-Wad commented on src/components/Members/index.js
> +  let id = 1;
```suggestion
   {members.map((member, i) => {
            return (
              <tr key={member.id}>
                <td>{++i}</td>
```

2020-11-05 12:39 UTC, Werton-Wad commented on src/components/Members/index.js
> +              <tr key={id}>
did as above

2020-11-05 12:39 UTC, Werton-Wad commented on src/components/Members/index.js
> +                <td>{member.firstName + ' ' + member.lastName}</td>
```suggestion
                 {members.map((member, i) => {
            return (
              <tr key={member.id}>
                <td>{++i}</td>
                <td>{getFullName(member.firstName, member.lastName)}</td>
```

2020-11-05 19:02 UTC, maximsan requested changes
Please, mark required fields in prop-types, use rem instead of px where it possible. I left some notes. Fix them and I will merge the pr. Thanks! Good work!

2020-11-06 11:39 UTC, Werton-Wad commented on src/Sass/Components/_header.scss
> +  .header__title {
it turned out so:
&__title === <header__title />
I was looking for solutions, they are all redundant, it is better to leave it like this.

2020-11-06 11:41 UTC, Werton-Wad commented on src/Sass/Components/_members.scss
> +  margin-top: 20px;
i used rem in all my style modules, only for font-size used px.
```suggestion
  margin-top: 1.5rem;
```

2020-11-06 11:45 UTC, Werton-Wad commented on src/components/MemberProgress/index.js
> +    progress: PropTypes.array,
i rewrote prop-type for all components)
```suggestion
firstName: PropTypes.string.isRequired,
    lastName: PropTypes.string.isRequired,
    startDate: PropTypes.number.isRequired,
    progress: PropTypes.array.isRequired,
```

2020-11-06 15:51 UTC, maximsan approved these changes
Hello! It looks good. You need 2 approves

2020-11-06 15:51 UTC, maximsan commented on src/Sass/Components/_header.scss
> +  .header__title {
Please, explain it on Tuesday, I do not understand what you mean

2020-11-06 17:08 UTC, VadimAlkhimenok approved these changes
Hi! It's a good work. Not questions. Approve.

2020-11-06 17:08 UTC, VadimAlkhimenok commented on src/components/MemberTasks/index.js
> +            <th>Dedline</th>
Deadline

2020-11-07 15:49 UTC, merged