Feature/pages second part
Dev-incubator/DIMS.UI-11 pull request #2
Opened 2021-01-14 12:58 UTC by chiburashka47

added components and functional from second part of the project.

2021-01-16 18:54 UTC, maximsan requested changes
Hello! I Left some notes, fix please.

2021-01-16 18:54 UTC, maximsan commented on src/services/data.json
>        "deadline": "12.12.2017"
Do you still need the file ?

2021-01-16 18:54 UTC, maximsan commented on src/services/firebase.js
> +import 'firebase/analytics';
I believe you can delete it.

2021-01-16 18:54 UTC, maximsan commented on src/services/services.js
> +  const regExp = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
move it to global scope

2021-01-16 18:54 UTC, maximsan commented on src/services/services.js
> +  return true;
U can just write `return length > 8`

2021-01-16 18:54 UTC, maximsan commented on src/services/services.js
> +export const isCorrectPassword = (password) => {
use `({ length })` or `(length)`

2021-01-16 18:54 UTC, maximsan commented on src/services/services.js
> +    throw new Error('Check your login and password');
Any `throw new Error` is not a good idea on UI. In that case you must not forget to handle it.

2021-01-16 18:54 UTC, maximsan commented on src/services/services.js
> +    return false;
Can we simplify it ? It can be `return Boolean(user)`.. but you also can handle it directly in component.
Don't need to mark method as `async` if you do not use `await`

2021-01-16 18:54 UTC, maximsan commented on src/services/services.js
> +export const getDataFirebase = async (collection, field) => {
Don't need to mark method as `async` if you do not use `await`

2021-01-16 18:54 UTC, maximsan commented on src/pages/Login.jsx
> +      if (await loginFirebase(email, password)) {
move result in separate variable

2021-01-16 18:54 UTC, maximsan commented on src/pages/Login.jsx
> +        const data = firebase.auth();
Is it not awaitable ?

2021-01-16 18:54 UTC, maximsan commented on src/pages/Login.jsx
> +        window.localStorage.setItem('userId', data.X);
create helper service or methods for work with local storage

2021-01-16 18:54 UTC, maximsan commented on src/pages/Login.jsx
> +  }
create one input method, u don't need 2

2021-01-16 18:54 UTC, maximsan commented on src/components/TableLine/TableLine.jsx
> +      {propsOtherFiedls.map(([key, value]) => (
...Fields

2021-01-16 18:54 UTC, maximsan commented on src/components/TableLine/style/TableLine.scss
> +      -webkit-box-orient: vertical;
why do u need it ? CRA has built-in auto-prefixier for browsers

2021-01-16 18:54 UTC, maximsan commented on src/index.scss
> +#root,
it looks like redundant work

2021-01-16 18:54 UTC, maximsan commented on src/components/SideBar/SideBar.jsx
> +          }}
`onClick={() => onClick(index)}`

2021-01-16 18:54 UTC, maximsan commented on src/components/PublicRoute/PublicRoute.jsx
> +);
Any route except `PrivateRoute` is already public. You don't really need it.

2021-01-16 18:54 UTC, maximsan commented on src/components/Loader/style/loader.scss
> +  --box-border-radius: 15%;
why do you suddenly decide to use variables ?

2021-01-16 18:54 UTC, maximsan commented on src/components/Loader/style/loader.scss
> +      box-shadow: 0px 0px 10px 0px rgba(#1c9fff, 0.4);
move colors to variables to

2021-01-16 18:54 UTC, maximsan commented on src/components/Loader/style/loader.scss
> +      background-color: #23d3fb;
move colors to variables to

2021-01-16 18:54 UTC, maximsan commented on src/components/Loader/style/loader.scss
> +    background-color: #1795ff;
move colors to variables to

2021-01-16 18:54 UTC, maximsan commented on src/components/Loader/style/loader.scss
> +    background-color: #23d3fb;
move colors to variables to

2021-01-16 18:54 UTC, maximsan commented on src/components/Loader/Loader.jsx
> +    <div className='loader__elem' />
it's better to create an array and generate a key for each elem

2021-01-16 18:54 UTC, maximsan commented on src/components/Header/Header.jsx
> +      if (userId) {
`if (!userName && userId)`

2021-01-16 18:54 UTC, maximsan commented on src/components/Header/Header.jsx
> +        if (userData && userData?.name) {
`if (userData?.name) {`

2021-01-16 18:54 UTC, maximsan commented on src/App/App.jsx
> +  }
`changeSideBarElem(activeElem) {
    this.setState({ activeElem });
  }`

2021-01-16 18:54 UTC, maximsan commented on src/App/App.jsx
> +      this.changeSideBarElem(1);
0, 1, 2 - are looks like magic numbers. change your logic, it's a bad approach

2021-01-16 18:54 UTC, maximsan commented on src/App/App.jsx
> +    const pathName = document.location.pathname;
`const { pathName } = document.location;`

2021-01-16 18:54 UTC, maximsan commented on src/App/App.jsx
> +    super(props);
`super(props)` must be called if you pass props, not necessary to call it every time

2021-01-16 18:54 UTC, maximsan commented on src/App/App.jsx
> +    } else this.changeSideBarElem(0);
wrap code in the brackets, it's a bad practice to omit the brackets

2021-01-16 18:54 UTC, maximsan commented on src/components/SideBar/SideBar.jsx
> +      {sideBaerList.map((item, index) => (
`...sideBarList`

2021-01-17 10:39 UTC, chiburashka47 commented on src/services/firebase.js
> +import 'firebase/analytics';
thx, i deleted this.

2021-01-17 10:46 UTC, chiburashka47 commented on src/services/services.js
> +  return true;
thx for the advice, i  did it.
```suggestion
  password.length >= 8
```

2021-01-17 10:48 UTC, chiburashka47 commented on src/services/services.js
> +export const isCorrectPassword = (password) => {
thx for the advice, i  did it.
```suggestion
 isCorrectPassword = ({ length }) => length >= 8;
```

2021-01-17 11:09 UTC, chiburashka47 commented on src/services/data.json
>        "deadline": "12.12.2017"
no, i deleted this file.

2021-01-17 11:14 UTC, chiburashka47 commented on src/services/services.js
> +  const regExp = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
could you explain this? i removed eslint exception
```suggestion
export const isCorrectEmail = (email) => {
  const regExp = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
  return regExp.test(email);
};
```

2021-01-17 11:15 UTC, chiburashka47 commented on src/services/services.js
> +    throw new Error('Check your login and password');
okey, thx. i change it.

2021-01-17 11:17 UTC, chiburashka47 commented on src/services/services.js
> +    return false;
thx, i changed this.
```suggestion
    export const getUserStatus = async () => {
  await firebase.auth().onAuthStateChanged((user) => Boolean(user));
};
```

2021-01-17 11:17 UTC, chiburashka47 commented on src/services/services.js
> +export const getDataFirebase = async (collection, field) => {
thx, i changed this.
```suggestion
    export const getUserStatus = async () => {
  await firebase.auth().onAuthStateChanged((user) => Boolean(user));
};
```

2021-01-17 11:26 UTC, chiburashka47 commented on src/pages/Login.jsx
> +      if (await loginFirebase(email, password)) {
thx, i chaged it.
```suggestion
      const loginUser = await loginFirebase(email, password);
      if (loginUser) {
```

2021-01-17 11:27 UTC, chiburashka47 commented on src/pages/Login.jsx
> +        const data = firebase.auth();
thx, i added it.
```suggestion
        const data = await firebase.auth();
```

2021-01-17 11:28 UTC, chiburashka47 commented on src/pages/Login.jsx
> +        window.localStorage.setItem('userId', data.X);
i deleted it, i don't need this functional anymore. Thx for advice.

2021-01-17 11:29 UTC, chiburashka47 commented on src/pages/Login.jsx
> +  }
thx, i changed if
```suggestion
  inputChange(value, field) {
    this.setState({ [field]: value });
  }
```

2021-01-17 11:32 UTC, chiburashka47 commented on src/components/TableLine/TableLine.jsx
> +      {propsOtherFiedls.map(([key, value]) => (
thx for attentiveness, it's so ashamed for me
```suggestion
      {propsOtherFields.map(([key, value]) => (
```

2021-01-17 11:37 UTC, chiburashka47 commented on src/components/TableLine/style/TableLine.scss
> +      -webkit-box-orient: vertical;
thx, i deleted it.

2021-01-17 11:41 UTC, chiburashka47 commented on src/index.scss
> +#root,
i think you right, i changed this place 
```suggestion
html,
#root,
.wrapper {
  height: 100%;
}
```

2021-01-17 11:46 UTC, chiburashka47 commented on src/components/SideBar/SideBar.jsx
> +          }}
thx, i don't use onClick anymore.

2021-01-17 11:52 UTC, chiburashka47 commented on src/components/PublicRoute/PublicRoute.jsx
> +);
thx i deleted this component.

2021-01-17 11:55 UTC, chiburashka47 commented on src/components/Loader/style/loader.scss
> +  --box-border-radius: 15%;
I took loader from another resources, and don't changed all of loader. Because I can't think of such a beautiful one)

2021-01-17 11:58 UTC, chiburashka47 commented on src/components/Loader/style/loader.scss
> +    background-color: #1795ff;
thx, i wrote all repeating colors to variables

2021-01-17 11:58 UTC, chiburashka47 commented on src/components/Loader/style/loader.scss
> +      background-color: #23d3fb;
thx, i wrote all repeating colors to variables

2021-01-17 11:58 UTC, chiburashka47 commented on src/components/Loader/style/loader.scss
> +      box-shadow: 0px 0px 10px 0px rgba(#1c9fff, 0.4);
thx, i wrote all repeating colors to variables

2021-01-17 11:58 UTC, chiburashka47 commented on src/components/Loader/style/loader.scss
> +    background-color: #23d3fb;
thx, i wrote all repeating colors to variables

2021-01-17 12:10 UTC, chiburashka47 commented on src/components/Loader/Loader.jsx
> +    <div className='loader__elem' />
thx, i changed this element. 
```suggestion
  {loaderElementsList.map((item) => (
      <div key={item} className='loader__elem' />
    ))}
```

2021-01-17 12:12 UTC, chiburashka47 commented on src/components/Header/Header.jsx
> +      if (userId) {
thx, i deleted request from this element.

2021-01-17 12:12 UTC, chiburashka47 commented on src/components/Header/Header.jsx
> +        if (userData && userData?.name) {
thx, i deleted request from this element.

2021-01-17 12:12 UTC, chiburashka47 commented on src/App/App.jsx
> +      this.changeSideBarElem(1);
thx, i chaged it

2021-01-17 12:14 UTC, chiburashka47 commented on src/App/App.jsx
> +    const pathName = document.location.pathname;
thx, i deleted request from this element.

2021-01-17 12:16 UTC, chiburashka47 commented on src/App/App.jsx
> +    super(props);
thx, i deleted this.

2021-01-17 12:16 UTC, chiburashka47 commented on src/App/App.jsx
> +    } else this.changeSideBarElem(0);
thx, i deleted this code from this element.

2021-01-17 12:18 UTC, chiburashka47 commented on src/components/SideBar/SideBar.jsx
> +      {sideBaerList.map((item, index) => (
thx for attentiveness, it's so ashamed for me)
```suggestion
      {sideBarList.map((item, index) => (
```

2021-01-17 12:18 UTC, chiburashka47 commented on src/App/App.jsx
> +  }
thx, i deleted this code from this element.

2021-01-17 20:36 UTC, maximsan commented on src/services/services.js
> +  const regExp = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
it's a good approach to save constant variables outside the methods

2021-01-17 20:45 UTC, maximsan commented on src/components/PublicRoute/PublicRoute.jsx
> +);
I guess you do some extra work. I believe you don't need all these checks. You also can use `React.context` here to simplify the logic.

2021-01-17 20:56 UTC, maximsan commented on src/services/services.js
> +    return false;
I guess you can even do like this `await firebase.auth().onAuthStateChanged(Boolean)`

2021-01-17 21:10 UTC, maximsan approved these changes
Hello, fix notes and then we will merge it. Good work!

2021-01-17 21:10 UTC, maximsan commented on src/App/App.jsx
> +          tasksData: Object.values(tasksData),
Can we just return values from your method  `getDataFirebase` without this extra code?

2021-01-17 21:10 UTC, maximsan commented on src/pages/Login.jsx
> +              onChange={(item) => this.inputChange(item.target.value, 'email')}
`onChange={this.inputChange}` is enough, and add name attribute, after this just spread everything you need from event object in method 
`const { name, value } = event.target;`

2021-01-18 08:21 UTC, chiburashka47 commented on src/services/services.js
> +  const regExp = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
Thx, now I understand.

2021-01-18 08:52 UTC, chiburashka47 commented on src/App/App.jsx
> +        const tasksData = await getDataFirebase('data', 'tasks');
thx, i changed it.
```suggestion
       const promise = Promise.all([
          getUserDataFirebase('data', 'users'),
          getDataFirebase('data', 'users'),
          getDataFirebase('data', 'tasks'),
        ]);
        promise.then(([userData, membersData, tasksData]) => {
          this.setState({
            userData: userData[user.uid],
            membersData,
            tasksData,
            isAuth: true,
            isDataLoad: true,
          });
```

2021-01-18 08:52 UTC, chiburashka47 commented on src/App/App.jsx
> +          tasksData: Object.values(tasksData),
thx, i changed it.
```suggestion
       const promise = Promise.all([
          getUserDataFirebase('data', 'users'),
          getDataFirebase('data', 'users'),
          getDataFirebase('data', 'tasks'),
        ]);
        promise.then(([userData, membersData, tasksData]) => {
          this.setState({
            userData: userData[user.uid],
            membersData,
            tasksData,
            isAuth: true,
            isDataLoad: true,
          });
```

2021-01-18 08:59 UTC, chiburashka47 commented on src/pages/Login.jsx
> +              onChange={(item) => this.inputChange(item.target.value, 'email')}
Thx for that, it's much more convenient.
```suggestion
    inputChange(event) {
    const { type, value } = event.target;
    this.setState({ [type]: value });
    ...
     <input type='password' className='login__container__row__input' onChange={this.inputChange} />
  }
```

2021-01-18 10:39 UTC, maximsan reviewed
It's better, but we can improve it more. Do what we've discussed in community chat.

2021-01-18 17:14 UTC, maximsan submitted a review, later dismissed
Not it's ok, but we need to make **Travis CI** and **Netlify** build green in **README-pr** and than we will proceed with merging. Can you handle it ?

2021-01-20 06:20 UTC, artur-nikitsin reviewed
Hi! Good work! I left some comments

2021-01-20 06:20 UTC, artur-nikitsin commented on src/components/Header/Header.jsx
> +        <Button className='header__content__user__btn' onClick={() => logoutFirebase()}>
This suntax create new callback with each render.

2021-01-20 06:20 UTC, artur-nikitsin commented on src/pages/MemberProgress.jsx
>  const tableNavigationFields = [
You can create separate file, something like "fields-template" and move it here

2021-01-20 06:20 UTC, artur-nikitsin commented on src/pages/MemberTasks.jsx
>  const tableNavigationFields = [
Also here

2021-01-20 10:41 UTC, chiburashka47 commented on src/components/Header/Header.jsx
> +        <Button className='header__content__user__btn' onClick={() => logoutFirebase()}>
thanks i fixed it
```suggestion
       <Button className='header__content__user__btn' onClick={hadleClick}>
```

2021-01-20 11:22 UTC, chiburashka47 commented on src/pages/MemberProgress.jsx
>  const tableNavigationFields = [
thx, i created the file.

2021-01-20 11:22 UTC, chiburashka47 commented on src/pages/MemberTasks.jsx
>  const tableNavigationFields = [
thx, i created the file.

2021-01-20 15:03 UTC, maximsan approved these changes
Looks ok

2021-01-20 16:47 UTC, DzmitryI commented on src/components/Loader/style/loader.scss
>    --box-size: 33px;
Try to use rem instead of px when your size more than 16px;

2021-01-23 16:16 UTC, maximsan approved these changes

2021-01-25 11:03 UTC, YauhenKoipish commented on src/components/Loader/style/loader.scss
>    --box-size: 33px;
thx, i will try it.

2021-01-25 18:12 UTC, maximsan approved these changes

2021-01-25 18:13 UTC, merged