Feature/pages third part
Dev-incubator/DIMS.UI-11 pull request #4
Opened 2021-01-28 15:44 UTC by YauhenKoipish

2021-01-29 16:30 UTC, maximsan requested changes
Hello! Please, fix my notes. Most of them applicable to all components/pages

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/MemberForm/MemberForm.jsx
> +  memberData: PropTypes.objectOf(PropTypes.any),
don't use any, specify object shape

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskForm/TaskForm.jsx
> +      membersData.forEach((item) => {
use map and spread

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskForm/TaskForm.jsx
> +      });
use callback version of setState

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskForm/TaskForm.jsx
> +    this.setState({ members });
use map, do not mutate  and callback version of setState

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskForm/TaskForm.jsx
> +    }
I will not repeat, but do the same as in previous component

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskForm/TaskForm.jsx
> +    this.setState({ [id]: value });
I will not repeat, but do the same as in previous component

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskForm/TaskForm.jsx
> +    const formTitle = isEditMode || isReadOnly ? `Task -  ${taskData.name}` : 'Create task';
create helper method with unit tests

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskForm/TaskForm.jsx
> +                  {membersData.map((item) => (
spread item

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskForm/TaskForm.jsx
> +                  handleClickShowTaskForm();
I will not repeat, but do the same as in previous component

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskTrackForm/TaskTrackForm.jsx
> +        this.setState({ name: item.name });
spread, use short props name

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/TaskTrackForm/TaskTrackForm.jsx
> +  taskData: PropTypes.objectOf(PropTypes.any),
I will not repeat, but do the same as in previous component

2021-01-29 16:30 UTC, maximsan commented on src/components/Forms/style/form.scss
> +      font-size: 24px;
use rem instead of px whenever it's possible

2021-01-29 16:30 UTC, maximsan commented on src/components/SideBar/style/sideBar.scss
> +      // }
remove

2021-01-29 16:30 UTC, maximsan commented on src/components/SideBar/style/sideBar.scss
> +        color: white;
use variable

2021-01-29 16:30 UTC, maximsan commented on src/components/TableLine/TableLine.jsx
> +export const TableLine = ({ number, name, children, btnHandleClick, path, isButtonLink, ...restProps }) => {
just `onClick` or `handleClick` is not enough for you ? don't create difficult names where you do not need it

2021-01-29 16:30 UTC, maximsan commented on src/components/TableLine/TableLine.jsx
> +  const location = useLocation();
spread what you need

2021-01-29 16:30 UTC, maximsan commented on src/pages/MemberProgress.jsx
> +      this.setState({ tasksData, isDataEmpty: tasksData[0], isDataLoad: true });
use callback version of setState

2021-01-29 16:30 UTC, maximsan commented on src/pages/MemberProgress.jsx
> +                tasksData.map((item, index) => (
srpead item

2021-01-29 16:30 UTC, maximsan commented on src/pages/MemberTasks.jsx
> +                        onClick={() => this.handleClickShowTaskTrackForm(item.taskId, item.name)}
move to the method

2021-01-29 16:30 UTC, maximsan commented on src/pages/Members.jsx
> +                  this.handleClickDetailMember(item.userId);
move to the method

2021-01-29 16:30 UTC, maximsan commented on src/pages/Members.jsx
> +                <Button onClick={() => this.handleClickSetMemberData(item.userId)} className='btn btn-line'>
move to the method

2021-01-29 16:30 UTC, maximsan commented on src/pages/Members.jsx
> +                <Button onClick={() => deleteUserById(item.userId)} className='btn btn-line btn-red'>
move to the method

2021-01-29 16:30 UTC, maximsan commented on src/pages/PasswordChange.jsx
> +  async buttonHandleCLick() {
`handleClick` is enough

2021-01-29 16:30 UTC, maximsan commented on src/pages/PasswordChange.jsx
> +    super();
You should be careful. Call `super(props)`  or do not do it

2021-01-29 16:30 UTC, maximsan commented on src/pages/TaskTracks.jsx
> +                        this.handleClickSetTasksTrackData(item.subTaskId);
move to the method

2021-01-29 16:30 UTC, maximsan commented on src/pages/TaskTracks.jsx
> +                        deleteSubTaskById(item.userId, item.taskId, item.subTaskId);
move to the method

2021-01-29 16:30 UTC, maximsan commented on src/pages/TaskTracks.jsx
> +                      this.handleClickDetailTaskTrack(item.subTaskId);
move to the method

2021-01-29 16:30 UTC, maximsan commented on src/pages/TaskTracks.jsx
> +              isDataEmpty ? (
Move to method with `if else`

2021-01-29 16:30 UTC, maximsan commented on src/pages/Tasks.jsx
> +                <Button onClick={() => this.handleClickSetTasksData(item.taskId)} className='btn btn-line '>
move to the method

2021-01-29 16:30 UTC, maximsan commented on src/pages/Tasks.jsx
> +                <Button onClick={() => deleteTaskById(item.taskId)} className='btn btn-line btn-red'>
move to the method

2021-01-29 16:30 UTC, maximsan commented on src/services/services.js
> +      // doc.data() will be undefined in this case
remove

2021-01-29 16:30 UTC, maximsan commented on src/services/services.js
> +  await firebase.auth().onAuthStateChanged((user) => Boolean(user));
`onAuthStateChanged(Boolean)` is the same

2021-01-29 16:30 UTC, maximsan commented on src/services/services.js
> +      // doc.data() will be undefined in this case
remove

2021-01-29 16:30 UTC, maximsan commented on src/services/services.js
> +    )
it can be a separate method, avoid code duplication

2021-01-29 16:30 UTC, maximsan commented on src/services/services.js
> +      console.error('Error writing document: ', error);
create helper. avoid duplication

2021-01-29 16:30 UTC, maximsan commented on src/services/services.js
> +      console.log('Document successfully written!');
create helper. avoid duplication

2021-01-29 16:30 UTC, maximsan commented on src/services/services.js
> +      });
use map and/ or  reduce

2021-01-29 16:30 UTC, maximsan commented on src/services/services.js
> +          if (doc.data()[userId][taskId]) {
avoid if nesting, it's a very bad code

2021-01-29 16:30 UTC, maximsan commented on src/services/services.js
> +      }
use map or reduce

2021-01-30 08:38 UTC, YauhenKoipish commented on package.json
> +    "install": "^0.13.0",
I removed this module, next time I will be more careful

2021-01-30 08:38 UTC, YauhenKoipish commented on package.json
> +    "reactstrap": "^8.8.1",
I removed this module, next time I will be more careful

2021-01-30 09:33 UTC, YauhenKoipish commented on src/App/App.jsx
> +            .onSnapshot((doc) => {
A onSnapshot can give results multiple times. That's why onSnapshot doesn't return a promise.

2021-01-30 09:34 UTC, YauhenKoipish commented on src/App/App.jsx
> +            .onSnapshot((doc) => {
A onSnapshot can give results multiple times. That's why onSnapshot doesn't return a promise. And i can't get real time updates from method

2021-01-30 09:40 UTC, YauhenKoipish commented on src/App/App.jsx
> +                condition={isAuth && !isVerified}
conditions it's a check Value for PrivateRoute, i don't need to use react.createcontext, because i use this conditions in PrivateRoute only.

2021-01-30 09:43 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +const rolesList = ['ADMIN', 'MENTOR', 'MEMBER'];
Thx, i did it.

2021-01-30 09:45 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +    const form = event.currentTarget;
thx, i changed it.
```suggestion
  const { currentTarget } = event;
```

2021-01-30 09:48 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +    this.setState({ validated: true });
it's a flag for standart Form validation and for input show validation.

2021-01-30 09:50 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +      const fullName = nameGluing(name, lastName);
I renamed it.
```suggestion
      const fullName = createFullName(name, lastName);
```

2021-01-30 09:56 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +        userId = memberData.userId;
thx for it, i changed it.
```suggestion
      ({ userId } = memberData);
```

2021-01-30 09:59 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +        await setUserValidation(userId, isEditMode);
I don't need to use await here at all, thanks for the comment.
```suggestion
        setUserValidation(userId, isEditMode);
```

2021-01-30 10:08 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +    let userId;
thx for idea, i changed it.
```suggestion
 if (currentTarget.checkValidity() === true) {
  const userId = isEditMode ? memberData.userId : await registerUser(email, password, fullName, false);
```

2021-01-30 10:13 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +    this.setState({ [id]: value });
It is convenient to use controlId with Form.Group in this case for me.

2021-01-30 11:26 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +                defaultValue={name}
I don't understand why to get rid of the type string? Is this a bad option?

2021-01-30 11:26 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +              </Form.Control>
I don't understand why to get rid of the type string? Is this a bad option?

2021-01-30 11:26 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +              />
I don't understand why to get rid of the type string? Is this a bad option?

2021-01-30 12:03 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +                  handleClickShowMemberForm();
thx, i created a method.
```suggestion
                  <Button onClick={this.handleClickBackToGrid} className='btn btn-white '>
```

2021-01-30 12:08 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +  memberData: PropTypes.objectOf(PropTypes.any),
Prop type `object` is forbidden eslint.

2021-01-30 12:40 UTC, YauhenKoipish commented on src/components/Forms/TaskForm/TaskForm.jsx
> +      membersData.forEach((item) => {
i don't need to return a arr.

2021-01-30 12:49 UTC, YauhenKoipish commented on src/components/Forms/TaskForm/TaskForm.jsx
> +      });
can you explain it? Why do i need it?

2021-01-30 12:50 UTC, YauhenKoipish commented on src/components/Forms/TaskForm/TaskForm.jsx
> +    }
Okay, i did it.

2021-01-30 12:56 UTC, YauhenKoipish commented on src/components/Forms/TaskForm/TaskForm.jsx
> +    this.setState({ [id]: value });
It is convenient to use controlId with Form.Group in this case for me.

2021-01-30 13:08 UTC, YauhenKoipish commented on src/components/Forms/TaskForm/TaskForm.jsx
> +    this.setState({ members });
can you explain it? I can't undertand how to use it here?

2021-01-30 21:34 UTC, maximsan commented on src/App/App.jsx
> +            .onSnapshot((doc) => {
What is the problem to create reusable method ?

2021-01-30 21:35 UTC, maximsan commented on src/App/App.jsx
> +                condition={isAuth && !isVerified}
As you wish

2021-02-01 08:17 UTC, YauhenKoipish commented on src/App/App.jsx
> +            .onSnapshot((doc) => {
I understand now, thx for conditions.
```suggestion
              this.getRealtimeUpdateData('tasks', 'tasksData'),
```

2021-02-01 09:39 UTC, YauhenKoipish commented on src/components/Forms/TaskForm/TaskForm.jsx
> +    this.setState({ members });
```suggestion
    const members = { ...prevMembers };
    members[id] = !members[id];
    this.setState({ members });
```

2021-02-01 09:42 UTC, YauhenKoipish commented on src/components/Forms/TaskForm/TaskForm.jsx
> +                  {membersData.map((item) => (
i did it, thx.
```suggestion
               {membersData.map(({ userId, name: memberName, lastName }) => (
```

2021-02-01 09:42 UTC, YauhenKoipish commented on src/components/Forms/TaskForm/TaskForm.jsx
> +                  handleClickShowTaskForm();
Thx, i changed it.

2021-02-01 09:44 UTC, YauhenKoipish commented on src/components/Forms/TaskTrackForm/TaskTrackForm.jsx
> +        this.setState({ name: item.name });
thx, i changed it.
```suggestion
   this.setState({ name });
```

2021-02-01 09:45 UTC, YauhenKoipish commented on src/components/Forms/TaskTrackForm/TaskTrackForm.jsx
> +  taskData: PropTypes.objectOf(PropTypes.any),
Prop type object is forbidden eslint. So I am using objectOf.

2021-02-01 10:10 UTC, YauhenKoipish commented on src/components/SideBar/style/sideBar.scss
> +      // }
thx, i removed it.

2021-02-01 10:15 UTC, YauhenKoipish commented on src/components/Forms/style/form.scss
> +      font-size: 24px;
thx, i chaged it.
```suggestion
      font-size: 1.6rem
```

2021-02-01 10:15 UTC, YauhenKoipish commented on src/components/SideBar/style/sideBar.scss
> +        color: white;
thx, you right about it.
```suggestion
        color: $white;
```

2021-02-01 10:18 UTC, YauhenKoipish commented on src/components/TableLine/TableLine.jsx
> +export const TableLine = ({ number, name, children, btnHandleClick, path, isButtonLink, ...restProps }) => {
Thx, for the comment. I changed it.
```suggestion
export const TableLine = ({ number, name, children, handleClick, path, isButtonLink, ...restProps }) => {
```

2021-02-01 10:20 UTC, YauhenKoipish commented on src/components/TableLine/TableLine.jsx
> +  const location = useLocation();
thx, i chaged it.
```suggestion
  const { pathname } = useLocation();
```

2021-02-01 10:40 UTC, YauhenKoipish commented on src/pages/MemberProgress.jsx
> +      this.setState({ tasksData, isDataEmpty: tasksData[0], isDataLoad: true });
thx, I forgot about this method.
```suggestion
    this.setState(() => {
        const isDataEmpty = tasksData[0];
        const isDataLoad = true;

        return { tasksData, isDataEmpty, isDataLoad };
      });
    }
```

2021-02-01 10:43 UTC, YauhenKoipish commented on src/pages/MemberProgress.jsx
> +                tasksData.map((item, index) => (
thx, i did it.
```suggestion
              { taskId, subTaskId, name, startDate, date, description, note }
```

2021-02-01 13:29 UTC, YauhenKoipish commented on src/pages/MemberTasks.jsx
> +                        onClick={() => this.handleClickShowTaskTrackForm(item.taskId, item.name)}
```suggestion
                         btnTask={this.createTrackBtn(item.taskId, item.name)}
```

2021-02-01 13:37 UTC, YauhenKoipish commented on src/pages/Members.jsx
> +                  this.handleClickDetailMember(item.userId);
I do not understand why I need to create a method here, and how it should look like, please write what you mean.

2021-02-01 13:37 UTC, YauhenKoipish commented on src/pages/Members.jsx
> +                <Button onClick={() => this.handleClickSetMemberData(item.userId)} className='btn btn-line'>
I do not understand why I need to create a method here, and how it should look like, please write what you mean.

2021-02-01 13:37 UTC, YauhenKoipish commented on src/pages/Members.jsx
> +                <Button onClick={() => deleteUserById(item.userId)} className='btn btn-line btn-red'>
I do not understand why I need to create a method here, and how it should look like, please write what you mean.

2021-02-01 13:40 UTC, YauhenKoipish commented on src/pages/PasswordChange.jsx
> +  async buttonHandleCLick() {
Thx, i changed it.
```suggestion
  async handleCLick() {
```

2021-02-01 13:41 UTC, YauhenKoipish commented on src/pages/PasswordChange.jsx
> +    super();
yes, you right. Thx.
```suggestion
    super(props);
```

2021-02-01 13:41 UTC, YauhenKoipish commented on src/pages/TaskTracks.jsx
> +                        this.handleClickSetTasksTrackData(item.subTaskId);
I do not understand why I need to create a method here, and how it should look like, please write what you mean.

2021-02-01 13:41 UTC, YauhenKoipish commented on src/pages/TaskTracks.jsx
> +                        deleteSubTaskById(item.userId, item.taskId, item.subTaskId);
I do not understand why I need to create a method here, and how it should look like, please write what you mean.

2021-02-01 13:41 UTC, YauhenKoipish commented on src/pages/TaskTracks.jsx
> +                      this.handleClickDetailTaskTrack(item.subTaskId);
I do not understand why I need to create a method here, and how it should look like, please write what you mean.

2021-02-01 13:45 UTC, YauhenKoipish commented on src/services/services.js
> +      // doc.data() will be undefined in this case
thx, i removed it.

2021-02-01 13:47 UTC, YauhenKoipish commented on src/services/services.js
> +  await firebase.auth().onAuthStateChanged((user) => Boolean(user));
i delted it, i don't use this function anymore, thx.

2021-02-01 13:47 UTC, YauhenKoipish commented on src/services/services.js
> +      // doc.data() will be undefined in this case
thx, i removed it.

2021-02-01 13:50 UTC, YauhenKoipish commented on src/services/services.js
> +    )
I don't think it would be convenient to use that.

2021-02-01 13:54 UTC, YauhenKoipish commented on src/services/services.js
> +      console.log('Document successfully written!');
thx, icreated helper method.
```suggestion
      successfullyWrittenMessage();
```

2021-02-01 14:03 UTC, YauhenKoipish commented on src/services/services.js
> +      console.error('Error writing document: ', error);
thx, icreated helper method.
```suggestion
      errorWritingMessage(error)
```

2021-02-01 14:28 UTC, YauhenKoipish commented on src/services/services.js
> +      }
I would like to discuss these issues tomorrow, if possible, maybe I do not fully understand the possibilities of map

2021-02-01 14:34 UTC, YauhenKoipish commented on src/services/services.js
> +          if (doc.data()[userId][taskId]) {
i changed it, thx.
```suggestion
         if (doc.data()[userId] && doc.data()[userId][taskId]) {
        return Object.values(doc.data()[userId][taskId]);
      }
```

2021-02-01 14:38 UTC, YauhenKoipish commented on src/services/services.js
> +      });
I would like to discuss these issues tomorrow, if possible, maybe I do not fully understand the possibilities of map

2021-02-01 14:46 UTC, YauhenKoipish commented on src/services/services.js
> +      }
thx, i am use filter here.
```suggestion
 data = tasks.filter((item) => item.members[id] === true);
```

2021-02-01 15:02 UTC, YauhenKoipish commented on src/pages/TaskTracks.jsx
> +              isDataEmpty ? (
thx, i fixed it.
```suggestion
              {this.getPageData()}
```

2021-02-01 15:13 UTC, YauhenKoipish commented on src/components/Forms/TaskForm/TaskForm.jsx
> +    const formTitle = isEditMode || isReadOnly ? `Task -  ${taskData.name}` : 'Create task';
if isEditMode or isReadOnly  !== true, taskData === null. And i can't pass taskData.name to func.

2021-02-01 17:36 UTC, YauhenKoipish commented on src/pages/Tasks.jsx
> +                <Button onClick={() => this.handleClickSetTasksData(item.taskId)} className='btn btn-line '>
thx, i fixed it

2021-02-01 17:36 UTC, YauhenKoipish commented on src/pages/Tasks.jsx
> +                <Button onClick={() => deleteTaskById(item.taskId)} className='btn btn-line btn-red'>
thx, i fixed it

2021-02-02 11:12 UTC, Larkgronick approved these changes

2021-02-04 13:24 UTC, Larkgronick approved these changes

2021-02-06 19:39 UTC, DzmitryI approved these changes

2021-02-09 16:55 UTC, maximsan requested changes

2021-02-09 17:02 UTC, maximsan approved these changes

2021-02-09 17:07 UTC, merged