Feature/join redux
Dev-incubator/DIMS.UI-11 pull request #5
Opened 2021-02-10 15:51 UTC by YauhenKoipish

Add redux to project.

2021-02-13 12:54 UTC, Larkgronick submitted a review, later dismissed

2021-02-14 16:21 UTC, maximsan requested changes
Hello! I left several comments. Check them out, thanks!

2021-02-14 16:21 UTC, maximsan commented on src/components/Forms/MemberForm/MemberForm.jsx
> +class MemberForm extends Component {
use PureComponent whenever it's possible, read about it https://ru.reactjs.org/docs/react-api.html#reactpurecomponent

2021-02-14 16:21 UTC, maximsan commented on src/components/Forms/MemberForm/MemberForm.jsx
> +function mapStateToProps(state) {
spread state

2021-02-14 16:21 UTC, maximsan commented on src/components/Header/Header.jsx
> +  } = useSelector((state) => state.app);
we don't use hooks in this week, don't mix the approaches, use `connect`

2021-02-14 16:21 UTC, maximsan commented on src/components/SideBar/SideBar.jsx
> +  } = useSelector((state) => state.app);
we don't use hooks in this week, don't mix the approaches, use ```connect```

2021-02-14 16:21 UTC, maximsan commented on src/components/SideBar/SideBar.jsx
> +              className={`sideBar__container__elem ${document.location.pathname === path && 'active'}`}
```pathname ``` should be taken from react router dom props

2021-02-14 16:21 UTC, maximsan commented on src/store/actions/app.js
> +          dispatch(getSnapshot('tasks', 'tasksData')),
don't need to call dispatches in ```Promise.all```, it doesn't make sense

2021-02-14 18:12 UTC, artur-nikitsin reviewed
Hi! Nice Work!

2021-02-14 18:12 UTC, artur-nikitsin commented on src/components/SideBar/SideBar.jsx
> +        {role !== 'MEMBER' &&
You can store string values in separate object to avoid errors

2021-02-14 19:04 UTC, YauhenKoipish commented on src/App/App.jsx
> +        {isAuth ? <Redirect to='/password-change' /> : <Route path='/' render={() => <Login />} />}
thx, i fixed it

2021-02-14 19:19 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +function mapStateToProps(state) {
Thanks, I changed this, and in other files too.
```suggestion
function mapStateToProps({ members: { memberData, isEditMode, isReadOnly } }) {
```

2021-02-14 19:32 UTC, YauhenKoipish commented on src/store/actions/app.js
> +          dispatch(getSnapshot('tasks', 'tasksData')),
thx, i fixed this.

2021-02-14 19:33 UTC, YauhenKoipish commented on src/App/App.jsx
> +        {isAuth ? <Redirect to='/password-change' /> : <Route path='/' render={() => <Login />} />}
thx, i fixed it.
```suggestion
        {isAuth ? <Redirect to='/password-change' /> : <Route path='/' component={Login} />}
```

2021-02-14 19:36 UTC, YauhenKoipish commented on src/components/SideBar/SideBar.jsx
> +              className={`sideBar__container__elem ${document.location.pathname === path && 'active'}`}
thx, i fixed it.

2021-02-14 19:43 UTC, YauhenKoipish commented on src/components/SideBar/SideBar.jsx
> +        {role !== 'MEMBER' &&
thx for it, i changed it.

2021-02-14 20:05 UTC, YauhenKoipish commented on src/components/Header/Header.jsx
> +  } = useSelector((state) => state.app);
Thx, i fixed it.

2021-02-14 20:05 UTC, YauhenKoipish commented on src/components/SideBar/SideBar.jsx
> +  } = useSelector((state) => state.app);
Thx, i fixed it.

2021-02-14 20:15 UTC, YauhenKoipish commented on src/components/Forms/MemberForm/MemberForm.jsx
> +class MemberForm extends Component {
thx, I fixed it, I will keep this in mind in the future.

2021-02-15 19:50 UTC, maximsan approved these changes
Looks ok. I will proceed with merge, but need more approves

2021-02-16 11:12 UTC, Larkgronick commented on src/App/App.jsx
> +import TaskTracks from '../pages/TaskTracks';
You can use multiimport here. It looks like that:
```
//App.jsx
import { Members, MemberProgress , MemberTasks, Tasks ,  TaskTracks  } from './index';
```
Before that you need to create separate index.js file, in wich you can place all components:
```
//index.js
export { Members } from '../pages/Members';
export { MemberProgress } from '../pages/MemberProgress ';
....
```

2021-02-16 11:18 UTC, Larkgronick approved these changes

2021-02-16 12:01 UTC, merged